### ISSUE TITLE
Add support for SVG image generation

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/images#2]
Would be nice if image svg placeholder images would be also generated during catalog image re-generation.

Potential solution is to set up https://hub.docker.com/r/fuww/sqip-server

eg:
```
docker pull fuww/sqip-server
docker run --rm -p 3000:3000 fuww/sqip-server
curl -X POST -F 'image=@/path/to/file.jpg' http://localhost:3000/ > file.svg
```
Or by using `docker-compose.yml`
```
version: '3'
services:
  sqip:
    image: fuww/sqip-server
    expose:
      - 3000
    ports:
      - 3000:3000
```

PHP could send processed images to the service and get the generated SVGs
